packages:
  - workflow
  - model
  - ui
  - test
  - software
  - block

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.6
  '@milaboratories/ts-configs': 1.2.1
  '@platforma-sdk/workflow-tengo': 5.8.2
  '@platforma-sdk/block-tools': 2.6.46
  '@platforma-sdk/model': 1.53.14
  '@platforma-sdk/ui-vue': 1.53.14
  '@platforma-sdk/test': 1.53.14
  '@platforma-sdk/tengo-builder': 2.4.16
  '@platforma-sdk/package-builder': 3.11.2
  '@platforma-sdk/eslint-config': 1.2.0
  '@milaboratories/strings': 0.1.0

  # Block-specific dependencies (can use ^ or ~)
  '@milaboratories/graph-maker': 1.1.223
  '@milaboratories/multi-sequence-alignment': 1.46.5
  '@platforma-open/milaboratories.runenv-python-3': 1.7.8
  '@platforma-open/milaboratories.runenv-python-3.12.10-parapred': 1.1.0
  '@platforma-open/soedinglab.software-mmseqs2': 1.17.1

  # Common dependencies - can use ^ or ~
  'typescript': ~5.6.3
  'turbo': ^2.6.1
  'vitest': ^4.0.10
  'eslint': ^9.25.1
  'vue': ^3.5.24
  'shx': ^0.4.0
  '@changesets/cli': ^2.29.7
